In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Bank_Marketing_Original_Data.csv')

In [3]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
df.isna().sum()

Age          0
Job          0
Marital      0
Education    0
Default      0
Balance      0
Housing      0
Loan         0
contact      0
Day          0
Month        0
Duration     0
Campaign     0
Pdays        0
Previous     0
poutcome     0
TARGET       0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        45211 non-null  int64
 1   Job        45211 non-null  str
 2   Marital    45211 non-null  str
 3   Education  45211 non-null  str
 4   Default    45211 non-null  str
 5   Balance    45211 non-null  int64
 6   Housing    45211 non-null  str
 7   Loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   Day        45211 non-null  int64
 10  Month      45211 non-null  str
 11  Duration   45211 non-null  int64
 12  Campaign   45211 non-null  int64
 13  Pdays      45211 non-null  int64
 14  Previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  TARGET     45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 8.1 MB

In [7]:
df['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [8]:
df['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [9]:
df['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [10]:
df['Default'].value_counts()

Default
no     44396
yes      815
Name: count, dtype: int64

In [11]:
df['Housing'].value_counts()

Housing
yes    25130
no     20081
Name: count, dtype: int64

In [12]:
df['Loan'].value_counts()

Loan
no     37967
yes     7244
Name: count, dtype: int64

In [13]:
df['contact'].value_counts()

contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64

In [14]:
df['Month'].value_counts()

Month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64

In [15]:
df['poutcome'].value_counts()

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [16]:
df['TARGET'].value_counts()

TARGET
no     39922
yes     5289
Name: count, dtype: int64

## Ordinal Encoder => Education
## Label Encoder => Target
## One Hot Encoder (Nominal Categorical) => Married, .....

In [17]:
ordinal_data = df[['Education']]

In [18]:
label_data = df[['TARGET']]

In [19]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['unknown', 'primary', 'secondary', 'tertiary']])

In [20]:
ordinal_data = oe.fit_transform(ordinal_data)

In [21]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

In [22]:
df['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
ld = le.fit_transform(label_data)

c:\Users\ManishAgrahari\Desktop\my_learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [25]:
ld

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

## One Hot Encoder

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
ohe = OneHotEncoder()

In [32]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
ohe.fit_transform(df[['Job']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 45211 stored elements and shape (45211, 12)>

In [34]:
nominal_data = df[['Job', 'Marital', 'Default', 'Housing', 'Loan', 'contact', 'Month', 'poutcome']]

In [35]:
nominal_data = ohe.fit_transform(nominal_data)
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 361688 stored elements and shape (45211, 40)>

## Feature Scaling

In [37]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [40]:
ss = StandardScaler()

In [41]:
num_col = df[['Age', 'Balance', 'Duration']]

In [42]:
ss.fit_transform(num_col)

array([[ 1.60696496,  0.25641925,  0.0110161 ],
       [ 0.28852927, -0.43789469, -0.41612696],
       [-0.74738448, -0.44676247, -0.70736086],
       ...,
       [ 2.92540065,  1.42959305,  3.37379688],
       [ 1.51279098, -0.22802402,  0.97014641],
       [-0.37068857,  0.52836436,  0.39932797]], shape=(45211, 3))

In [43]:
mms = MinMaxScaler()

In [44]:
mms.fit_transform(num_col)

array([[0.51948052, 0.09225936, 0.05307035],
       [0.33766234, 0.07306666, 0.03070354],
       [0.19480519, 0.07282153, 0.01545344],
       ...,
       [0.7012987 , 0.12468905, 0.22915819],
       [0.50649351, 0.07886805, 0.10329402],
       [0.24675325, 0.09977666, 0.07340382]], shape=(45211, 3))