In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('Bank_Marketing_Original_Data.csv')

In [3]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        45211 non-null  int64
 1   Job        45211 non-null  str
 2   Marital    45211 non-null  str
 3   Education  45211 non-null  str
 4   Default    45211 non-null  str
 5   Balance    45211 non-null  int64
 6   Housing    45211 non-null  str
 7   Loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   Day        45211 non-null  int64
 10  Month      45211 non-null  str
 11  Duration   45211 non-null  int64
 12  Campaign   45211 non-null  int64
 13  Pdays      45211 non-null  int64
 14  Previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  TARGET     45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 8.1 MB

## In this we have 16 Columns

## To which i can divide into 4 major parts as:
#### Numerical cols -> Scaling using StandardScale or MinMaxScale -> ['Balance', 'Duration']
#### Binary Cols -> Encoding using LabelEncoder or just mapping (1, 0) -> ['Default', 'Housing', 'Loan', 'TARGET']
#### Ordinal Categorial Cols -> Encoding using OrdinalEncoder -> ['Education']
#### Nominal Categorical Cols -> Encoding using OneHotEncoder -> ['Job', 'Marital', 'Month', 'poutcome']

In [6]:
oe = OrdinalEncoder(categories=[['unknown', 'primary', 'secondary', 'tertiary']])
df['Education'] = oe.fit_transform(df[['Education']])

In [7]:
df

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,3.0,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,2.0,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,2.0,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,0.0,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,0.0,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,3.0,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,1.0,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,2.0,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,2.0,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,2.0,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [22]:
num_cols = ['Balance', 'Day', 'Duration', 'Campaign', 'Pdays', 'Previous']

cat_cols = ['Job', 'Marital', 'Month', 'Housing', 'Loan', 'poutcome']

In [23]:
transformer = ColumnTransformer(transformers=[('cat', OneHotEncoder(), cat_cols), ('num', StandardScaler(), num_cols)], remainder='passthrough')

In [24]:
X = df.iloc[:, :-1]

In [25]:
Y = df['TARGET']

In [27]:
X = transformer.fit_transform(X)

In [28]:
X

array([[0.0, 0.0, 0.0, ..., 3.0, 'no', 'unknown'],
       [0.0, 0.0, 0.0, ..., 2.0, 'no', 'unknown'],
       [0.0, 0.0, 1.0, ..., 2.0, 'no', 'unknown'],
       ...,
       [0.0, 0.0, 0.0, ..., 2.0, 'no', 'cellular'],
       [0.0, 1.0, 0.0, ..., 2.0, 'no', 'telephone'],
       [0.0, 0.0, 1.0, ..., 2.0, 'no', 'cellular']],
      shape=(45211, 45), dtype=object)