In [1]:
import pandas as pd

In [2]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [3]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [4]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --------------------------------------- 0.0/11.9 MB 660.6 kB/s eta 0:00:18
      --------------------------------------- 0.3/11.9 MB 3.2 MB/s eta 0:00:04
     - -------------------------------------- 0.6/11.9 MB 5.3 MB/s eta 0:00:03
     --- ------------------------------------ 1.1/11.9 MB 7.2 MB/s eta 0:00:02
     ----- ---------------------------------- 1.7/11.9 MB 8.3 MB/s eta 0:00:02
     ------- -------------------------------- 2.1/11.9 MB 8.4 MB/s eta 0:00:02
     --------- ------------------------------ 2.7/11.9 MB 9.1 MB/s eta 0:00:02
     ---------- ----------------------------- 3.1/11.9 MB 9.6 MB/s eta 0:00:01
     ------------ --------------------------- 3.6/11.9 MB 9.5 MB/s eta 0:00:01
     ------------- -------------------------- 4.1/11.9 MB 10.0 MB/s eta 0:00:01
     --------------- ------------------------ 4.6/11.9 MB 10.1 MB/s eta 0:00:01
     ---------------- ----------------------- 5.0/11.9 MB 10.3 MB/s eta 0:00:01
     ------------------ --------------------- 5.5/11.9 MB 10.3 MB/s eta 0:00:01
     -------------------- ------------------- 5.9/11.9 MB 10.5 MB/s eta 0:00:01
     --------------------- ------------------ 6.4/11.9 MB 10.5 MB/s eta 0:00:01
     ----------------------- ---------------- 6.9/11.9 MB 10.5 MB/s eta 0:00:01
     ------------------------- -------------- 7.4/11.9 MB 10.8 MB/s eta 0:00:01
     --------------------------- ------------ 8.0/11.9 MB 10.9 MB/s eta 0:00:01
     ---------------------------- ----------- 8.5/11.9 MB 10.8 MB/s eta 0:00:01
     ------------------------------ --------- 8.9/11.9 MB 10.9 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 11.0 MB/s eta 0:00:01
     -------------------------------- ------ 10.0/11.9 MB 11.1 MB/s eta 0:00:01
     ---------------------------------- ---- 10.6/11.9 MB 11.9 MB/s eta 0:00:01
     ------------------------------------ -- 11.0/11.9 MB 11.9 MB/s eta 0:00:01
     --------------------------------------  11.6/11.9 MB 11.9 MB/s eta 0:00:01
     --------------------------------------  11.8/11.9 MB 11.9 MB/s eta 0:00:01
     --------------------------------------- 11.9/11.9 MB 11.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=248051 sha256=ce33002eff44dcdcef71a9d58f8ab4c4bc2045b51a96a3c75d2b9705437e3529
  Stored in directory: c:\users\manishagrahari\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [ ]:
mysql.connector.connect(host='localhost', username='root', password='', database='world')