## Deep Learning with 1M data points

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('huge_1M_titanic.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [5]:
df.shape

(1000000, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop(columns=['PassengerId', 'Name', 'Age', 'Ticket', 'Cabin'], inplace=True)

In [9]:
df.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [10]:
df.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [11]:
df['Embarked'].mode()

0    S
Name: Embarked, dtype: str

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Survived  1000000 non-null  int64
 1   Pclass    1000000 non-null  int64
 2   Sex       1000000 non-null  str
 3   SibSp     1000000 non-null  int64
 4   Parch     1000000 non-null  int64
 5   Fare      1000000 non-null  float64
 6   Embarked  997760 non-null   str
dtypes: float64(1), int64(4), str(2)
memory usage: 59.0 MB

In [13]:
df.Sex = df['Sex'].astype('category')
# df.Embarked = df['Embarked'].astype('category')
df.Survived = df['Survived'].astype('int32')
df.Pclass = df['Pclass'].astype('int32')
df.SibSp = df['SibSp'].astype('int32')
df.Parch = df['Parch'].astype('int32')

In [14]:
df.Embarked = df.Embarked.replace({'S': 'Southampton', 'C': 'Chebourg', 'Q': 'Queenstown'})

In [15]:
df.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165     Chebourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416     Chebourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769     Chebourg

In [16]:
df['Embarked'].value_counts()

Embarked
Southampton    729468
Chebourg       186846
Queenstown      81446
Name: count, dtype: int64

In [17]:
df.dropna(subset=['Embarked'], inplace=True)

In [18]:
df['Fare'] = df['Fare'].astype('int8')

In [19]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

## Feature Encoding
Label Encoding for column having 2 category

In [20]:
df.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76     Chebourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12     Chebourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4     Chebourg

In [21]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [22]:
le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])

In [23]:
ohe = OneHotEncoder(sparse_output=False)

Embarked = ohe.fit_transform(df[['Embarked']])

In [24]:
Embarked = pd.DataFrame(Embarked, columns=ohe.get_feature_names_out())

In [25]:
Embarked

        Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                     1.0                  0.0                   0.0
1                     0.0                  0.0                   1.0
2                     1.0                  0.0                   0.0
3                     0.0                  0.0                   1.0
4                     1.0                  0.0                   0.0
...                   ...                  ...                   ...
997755                0.0                  0.0                   1.0
997756                0.0                  0.0                   1.0
997757                0.0                  0.0                   1.0
997758                0.0                  0.0                   1.0
997759                0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [26]:
df = pd.concat([df.drop(columns=['Embarked']), Embarked], axis=1)

In [27]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

## Feature Scaling
Standardization and Normalization

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
num_cols = ['Pclass', 'SibSp', 'Parch', 'Fare']

In [30]:
scale = StandardScaler()

df[num_cols] = scale.fit_transform(df[num_cols])

In [31]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [32]:
import pickle

In [33]:
with open('lable_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

In [34]:
with open('one_hot_encoder.pkl', 'wb') as file:
    pickle.dump(ohe, file)

In [35]:
with open('scale.pkl', 'wb') as file:
    pickle.dump(scale, file)

## Train Test Validation Split

In [36]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [37]:
df.dropna(inplace=True)

In [38]:
X = df.drop(columns=['Survived'])

In [39]:
y = df['Survived']

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=42)

In [42]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
X_valid.shape

(199106, 8)

In [44]:
## ANN Implementation

In [45]:
import tensorflow

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [51]:
(X_train.shape[1],)

(8,)

In [65]:
model = Sequential(
    [
        Dense(128, input_shape=(X_train.shape[1],), activation='relu'), # First Hidden Layer
        Dense(64, activation='relu'), # First Hidden Layer
        Dense(32, activation='relu'), # Second Hidden Layer
        Dense(1, activation='sigmoid'), # Output Layer
    ]
)

c:\Users\ManishAgrahari\Desktop\my_learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,521 (45.00 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
tensorflow.keras.losses.BinaryFocalCrossentropy

keras.src.losses.losses.BinaryFocalCrossentropy

In [68]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [69]:
stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [70]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=10, callbacks=[stopping_callback])

Epoch 1/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 28s 1ms/step - accuracy: 0.8435 - loss: 0.3504 - val_accuracy: 0.8494 - val_loss: 0.3391
Epoch 2/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8504 - loss: 0.3378 - val_accuracy: 0.8495 - val_loss: 0.3381
Epoch 3/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8514 - loss: 0.3360 - val_accuracy: 0.8519 - val_loss: 0.3358
Epoch 4/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8518 - loss: 0.3351 - val_accuracy: 0.8510 - val_loss: 0.3413
Epoch 5/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8525 - loss: 0.3341 - val_accuracy: 0.8517 - val_loss: 0.3379
Epoch 6/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8522 - loss: 0.3347 - val_accuracy: 0.8524 - val_loss: 0.3332
Epoch 7/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8521 - loss: 0.3345 - val_accuracy: 0.8486 - val_loss: 0.3370
Epoch 8/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 25s 1ms/step - accuracy: 0.8516 - loss: 0.3350 - val_accuracy: 0.8526 - val_loss: 0.3387
Epoch 9/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 26s 1ms/step - accuracy: 0.8524 - loss: 0.3343 - val_accuracy: 0.8523 - val_loss: 0.3356
Epoch 10/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 27s 1ms/step - accuracy: 0.8524 - loss: 0.3343 - val_accuracy: 0.8527 - val_loss: 0.3392

In [71]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [72]:
from tensorflow.keras.models import load_model
import pickle
import tensorflow as tf

In [73]:
with open('lable_encoder.pkl', 'rb') as file:
    label = pickle.load(file)

In [74]:
with open('one_hot_encoder.pkl', 'rb') as file:
    one_hot = pickle.load(file)

In [76]:
with open('scale.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [77]:
trained_model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [78]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [98]:
user = {
    'Pclass': 1,
    'Sex': 'female',
    'SibSp': 2,
    'Parch': 1,
    'Fare': 76,
    'Embarked': 'Chebourg'
}

In [99]:
user = pd.DataFrame([user])

In [100]:
user

   Pclass     Sex  SibSp  Parch  Fare  Embarked
0       1  female      2      1    76  Chebourg

In [101]:
user['Sex'] = label.transform(user['Sex'])

In [102]:
embarked = one_hot.transform(user[['Embarked']])

In [103]:
embarked

array([[1., 0., 0.]])

In [104]:
embarked = pd.DataFrame(embarked, columns=one_hot.get_feature_names_out())
embarked

   Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                1.0                  0.0                   0.0

In [105]:
user = pd.concat([user.drop(columns=['Embarked']), embarked], axis=1)

In [106]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1,0,2,1,76,1.0,0.0,0.0

In [107]:
user[num_cols] = scaler.transform(user[num_cols])
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0,1.347567,0.833802,1.675922,1.0,0.0,0.0

In [108]:
y = trained_model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

In [109]:
y = y[0][0]

In [111]:
y

np.float32(0.9972618)

In [110]:
if y > 0.5:
    print('Higher chance to survive')
else:
    print('Less chance to survive')

Higher chance to survive