## Data Gathering

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('ai_dev_productivity.csv')

In [3]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hours_coding      500 non-null    float64
 1   coffee_intake_mg  500 non-null    int64
 2   distractions      500 non-null    int64
 3   sleep_hours       500 non-null    float64
 4   commits           500 non-null    int64
 5   bugs_reported     500 non-null    int64
 6   ai_usage_hours    500 non-null    float64
 7   cognitive_load    500 non-null    float64
 8   task_success      500 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [5]:
data.duplicated().sum()

np.int64(0)

In [6]:
data.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,5.015600,463.192000,2.976000,6.975800,4.60800,0.858000,1.510920,4.498200,0.606000
std,1.947253,142.334991,1.678409,1.455965,2.70499,1.102846,1.085557,1.868861,0.489124
min,0.000000,6.000000,0.000000,3.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,3.600000,369.500000,2.000000,6.100000,3.00000,0.000000,0.697500,3.175000,0.000000
50%,5.030000,500.500000,3.000000,6.950000,5.00000,0.000000,1.260000,4.400000,1.000000
75%,6.275000,600.000000,4.000000,7.900000,6.00000,2.000000,2.070000,5.800000,1.000000
max,12.000000,600.000000,8.000000,10.000000,13.00000,5.000000,6.360000,10.000000,1.000000

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [9]:
data.columns.to_list()

['hours_coding',
 'coffee_intake_mg',
 'distractions',
 'sleep_hours',
 'commits',
 'bugs_reported',
 'ai_usage_hours',
 'cognitive_load',
 'task_success']

In [10]:
num_cols = [
'hours_coding',
'coffee_intake_mg',
'distractions',
'sleep_hours',
'commits',
'bugs_reported',
'ai_usage_hours'
]

In [11]:
scaler = StandardScaler()

In [12]:
X = data.drop(columns=['cognitive_load'])

y = data['cognitive_load']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X_train.shape

(400, 8)

In [16]:
y_train.shape

(400,)

In [20]:
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])

In [22]:
X_test[num_cols] = scaler.fit_transform(X_test[num_cols])

In [23]:
X_train

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
249,0.410116,0.348814,-1.159772,1.628183,0.146206,-0.780969,0.050837,1
433,0.731716,0.508152,1.222301,-0.459879,-1.334364,-0.780969,0.634796,1
19,-1.442912,-1.424697,0.031265,-2.211156,-0.594079,-0.780969,-0.778007,0
322,-0.840550,-0.066853,0.031265,-0.527236,-0.964221,1.927593,0.493516,0
332,0.073202,0.030136,1.222301,-0.729306,-0.594079,-0.780969,0.465260,0
...,...,...,...,...,...,...,...,...
106,1.921126,0.965386,-0.564254,0.348403,0.146206,-0.780969,-0.420097,1
270,1.466802,0.965386,2.413338,1.224042,1.256634,-0.780969,0.041419,1
348,-0.738455,-0.946681,-0.564254,-0.594592,-0.223936,1.024739,-1.201848,0
435,0.073202,0.203330,-0.564254,1.156685,1.256634,-0.780969,-0.307073,1
102,-0.355598,0.099414,-1.159772,-0.998733,-0.594079,-0.780969,-0.373004,1

In [ ]:
y_train

249    3.3
433    5.7
19     8.2
322    6.5
332    8.1
      ...
106    1.9
270    4.3
348    4.2
435    2.1
102    4.9
Name: cognitive_load, Length: 400, dtype: float64

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [28]:
(X_train.shape[1],)

(8,)

In [29]:
model = Sequential(
    [
        Dense(64, input_shape=(X_train.shape[1],), activation='linear'),
        Dense(32, activation='linear'),
        Dense(1, activation='linear')
    ]
)

c:\Users\ManishAgrahari\Desktop\my_learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer='adam', metrics=['mae'], loss='mse')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [33]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 21.5051 - mae: 4.2690
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.8803 - mae: 3.6617
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8903 - mae: 2.9630
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5650 - mae: 2.1834
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.8195 - mae: 1.5601
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8399 - mae: 1.3472
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5615 - mae: 1.2842
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3607 - mae: 1.2432
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2405 - mae: 1.2047
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.1068 - mae: 1.1646
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.0123 - mae: 1.1400
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.9497 - mae: 1.1334
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7935 - mae: 1.0826
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7365 - mae: 1.0566
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6311 - mae: 1.0398
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5433 - mae: 1.0092
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5212 - mae: 0.9938
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4090 - mae: 0.9497
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3366 - mae: 0.9352
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2963 - mae: 0.9207
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2275 - mae: 0.8886
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1893 - mae: 0.8736
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1499 - mae: 0.8592
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1098 - mae: 0.8379
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0988 - mae: 0.8362
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0790 - mae: 0.8253
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0532 - mae: 0.8092
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0323 - mae: 0.8061
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0353 - mae: 0.8054
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0085 - mae: 0.8002
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0163 - mae: 0.7978
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0038 - mae: 0.7976
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0123 - mae: 0.7978
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0021 - mae: 0.7928
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9753 - mae: 0.7814
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9837 - mae: 0.7849
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9882 - mae: 0.7912
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9865 - mae: 0.7878
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9877 - mae: 0.7856
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9771 - mae: 0.7825
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9855 - mae: 0.7877
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9813 - mae: 0.7810
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9744 - mae: 0.7829
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9866 - mae: 0.7808
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9910 - mae: 0.7877
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9936 - mae: 0.7941
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9742 - mae: 0.7829
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9819 - mae: 0.7796
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9793 - mae: 0.7874
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0049 - mae: 0.7919
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9807 - mae: 0.7840
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0343 - mae: 0.8042
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0086 - mae: 0.7964
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0229 - mae: 0.8045
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9921 - mae: 0.7918
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9967 - mae: 0.7905
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0803 - mae: 0.8196
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0138 - mae: 0.8065
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0330 - mae: 0.8061
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0010 - mae: 0.7953
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9970 - mae: 0.7880
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9887 - mae: 0.7873
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9887 - mae: 0.7854
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9775 - mae: 0.7825
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0069 - mae: 0.7980
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9804 - mae: 0.7810
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9854 - mae: 0.7861
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0015 - mae: 0.7931
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9877 - mae: 0.7884
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9847 - mae: 0.7873
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9816 - mae: 0.7811
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9779 - mae: 0.7812
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9954 - mae: 0.7901
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9867 - mae: 0.7905
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0085 - mae: 0.7928
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9937 - mae: 0.7891
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9855 - mae: 0.7858
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9803 - mae: 0.7848
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9926 - mae: 0.7903
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9981 - mae: 0.7945
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9914 - mae: 0.7876
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9889 - mae: 0.7865
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9934 - mae: 0.7879
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9941 - mae: 0.7928
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0102 - mae: 0.7950
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9900 - mae: 0.7867
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0082 - mae: 0.7999
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0042 - mae: 0.7926
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9879 - mae: 0.7871
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9831 - mae: 0.7867
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9855 - mae: 0.7824
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9797 - mae: 0.7840
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9873 - mae: 0.7847
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9807 - mae: 0.7813
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9851 - mae: 0.7890
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9810 - mae: 0.7872
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9766 - mae: 0.7832
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9992 - mae: 0.7939
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9896 - mae: 0.7906
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0037 - mae: 0.7939

In [34]:
from sklearn.metrics import mean_squared_error

In [35]:
y_predict = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [36]:
mean_squared_error(y_predict, y_test)

0.9152331567176034